version: '3'

networks:
  magento22:

services:
  magento:
    image: alexcheng/magento2:2.2
    ports:
      - "30022:80"
    depends_on:
      - mysql
    networks:
      - magento22
    env_file:
      - env

  mysql:
    image: mysql:5.6.23
    networks:
      - magento22
    volumes:
      - ./mysql-data:/var/lib/mysql/data
    env_file:
      - env
