version: '3'

networks:
  magento23:

services:
  magento:
    image: alexcheng/magento2
    ports:
      - "30023:80"
    depends_on:
      - mysql
    networks:
      - magento23
    env_file:
      - env

  mysql:
    image: mysql:5.6.23
    networks:
      - magento23
    volumes:
      - ./mysql-data:/var/lib/mysql/data
    env_file:
      - env
