version: '3'

networks:
  magento21:

services:
  magento:
    image: alexcheng/magento2:2.1
    ports:
      - "30021:80"
    depends_on:
      - mysql
    networks:
      - magento21
    env_file:
      - env

  mysql:
    image: mysql:5.6.23
    networks:
      - magento21
    volumes:
      - ./mysql-data:/var/lib/mysql/data
    env_file:
      - env
